## **1. Data Load & Overview**

In [1]:
# 1.1 Load Data
import pandas as pd
import re
import nltk
import contractions
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

df = pd.read_csv("../1_data/processed/01_cleaned.csv")
print("Data loaded successfully!")
print(f"Shape: {df.shape}")

Data loaded successfully!
Shape: (22980, 16)

In [2]:
# 1.2 Download NLTK Data
import nltk
nltk.download('stopwords', quiet=True)
nltk.download('punkt', quiet=True)
nltk.download('wordnet', quiet=True)
nltk.download('omw-1.4', quiet=True)
nltk.download('punkt_tab', quiet=True)

True

In [3]:
# 1.3 Check Review Columns
for review in df["Review_Title"].values[:5]:
    print(review)
    print("---")

"pretty decent airline"
---
"Not a good airline"
---
"flight was fortunately short"
---
"I will never fly again with Adria"
---
"it ruined our last days of holidays"
---

In [4]:
for review in df["Review"].values[:5]:
    print(review)
    print("---")

  Moroni to Moheli. Turned out to be a pretty decent airline. Online booking worked well, checkin and boarding was fine and the plane looked well maintained. Its a very short flight - just 20 minutes or so so i didn't expect much but they still managed to hand our a bottle of water and some biscuits which i though was very nice. Both flights on time.
---
 Moroni to Anjouan. It is a very small airline. My ticket advised me to turn up at 0800hrs which I did. There was confusion at this small airport. I was then directed to the office of AB Aviation which was still closed. It opened at 0900hrs and I was told that the flight had been put back to 1300hrs and that they had tried to contact me. This could not be true as they did not have my phone number. I was with a local guide and he had not been informed either. I presume that I was bumped off. The later flight did operate but as usual, there was confusion at check-in. The flight was only 30mins and there were no further problems. Not a good airline but it is the only one for Comoros.
---
  Anjouan to Dzaoudzi. A very small airline and the only airline based in Comoros. Check-in was disorganised because of locals with big packages and disinterested staff. The flight was fortunately short (30 mins). Took off on time and landed on time. With a short flight like there was of course no in-flight entertainment nor cabin service except for biscuits and a bottle of water, which was quite nice!
---
  Please do a favor yourself and do not fly with Adria. On the route from Munich to Pristina in July 2019 they lost my luggage and for 10 days in a row, despite numerous phone calls they were not able to locate it. 11 days later the luggage arrived at the destination completely ruined. Applying for compensation, they ignored my request. Foolishly again, I booked another flight with them (345 euros) Frankfurt - Pristina in September 2019. They cancelled the flight with no reason 24 hours before the departure. Desperate phone calls to customer service to get anything (rerouting, compensation, etc) were not responded. I will never fly again with Adria. What a disgrace! Shame on you Adria for constantly deceiving your customers.
---
 Do not book a flight with this airline! My friend and I should have returned from Sofia to Amsterdam on September 22 and 3 days before, they sent us an SMS informing the flight was cancelled. For 3 straight days we tried to reach the airline and the web agent (e-dreams) and we did not get a solution. Finally, 18 hours before our cancelled flight time, and after 35 minutes on a call (waiting), the airline was able to get us on a flight with Lufthansa. Do not book Adria Airways, it is unreliable and in our case, it ruined our last days of holidays since we needed to be on the phones all day.
---

> ### **Text Input Strategy - Full Text (Title + Review)**
>
> The review title is prepended to the review body before preprocessing. As observed in the sample data, review titles tend to capture the core sentiment in a concise form (e.g., *"I will never fly again with Adria"*) and do not simply repeat the review body. Combining both is expected to enrich the sentiment signal, particularly for shorter reviews where the title may provide critical context.

In [5]:
# 1.4 Concatinate "Review_Title" to "Review"
df['Full_Review'] = df['Review_Title'].str.strip('"') + '. ' + df['Review'].str.strip()

# 1.5 Drop original columns
df = df.drop(columns=['Review_Title', 'Review'])

for review in df["Full_Review"].values[:5]:
    print(review)
    print("---")

pretty decent airline. Moroni to Moheli. Turned out to be a pretty decent airline. Online booking worked well, checkin and boarding was fine and the plane looked well maintained. Its a very short flight - just 20 minutes or so so i didn't expect much but they still managed to hand our a bottle of water and some biscuits which i though was very nice. Both flights on time.
---
Not a good airline. Moroni to Anjouan. It is a very small airline. My ticket advised me to turn up at 0800hrs which I did. There was confusion at this small airport. I was then directed to the office of AB Aviation which was still closed. It opened at 0900hrs and I was told that the flight had been put back to 1300hrs and that they had tried to contact me. This could not be true as they did not have my phone number. I was with a local guide and he had not been informed either. I presume that I was bumped off. The later flight did operate but as usual, there was confusion at check-in. The flight was only 30mins and there were no further problems. Not a good airline but it is the only one for Comoros.
---
flight was fortunately short. Anjouan to Dzaoudzi. A very small airline and the only airline based in Comoros. Check-in was disorganised because of locals with big packages and disinterested staff. The flight was fortunately short (30 mins). Took off on time and landed on time. With a short flight like there was of course no in-flight entertainment nor cabin service except for biscuits and a bottle of water, which was quite nice!
---
I will never fly again with Adria. Please do a favor yourself and do not fly with Adria. On the route from Munich to Pristina in July 2019 they lost my luggage and for 10 days in a row, despite numerous phone calls they were not able to locate it. 11 days later the luggage arrived at the destination completely ruined. Applying for compensation, they ignored my request. Foolishly again, I booked another flight with them (345 euros) Frankfurt - Pristina in September 2019. They cancelled the flight with no reason 24 hours before the departure. Desperate phone calls to customer service to get anything (rerouting, compensation, etc) were not responded. I will never fly again with Adria. What a disgrace! Shame on you Adria for constantly deceiving your customers.
---
it ruined our last days of holidays. Do not book a flight with this airline! My friend and I should have returned from Sofia to Amsterdam on September 22 and 3 days before, they sent us an SMS informing the flight was cancelled. For 3 straight days we tried to reach the airline and the web agent (e-dreams) and we did not get a solution. Finally, 18 hours before our cancelled flight time, and after 35 minutes on a call (waiting), the airline was able to get us on a flight with Lufthansa. Do not book Adria Airways, it is unreliable and in our case, it ruined our last days of holidays since we needed to be on the phones all day.
---

## **2. Text Pre-processing**

> ### **Preprocessing Strategy by Feature Set**
>
> - **Set A (Numerical Only)**: This set relies on numerical sub-ratings as features. Hence, text pre-processing is not required.
>
> - **Set B (VADER)**: Minimal preprocessing to preserve sentiment signals such as negations, punctuation emphasis (!, ?), and sentence structure. Stopword removal and tokenization are intentionally excluded as they may distort VADER's sentiment scoring.
>
> - **Set C (Rule-based Aspect Sentiment)**: Full preprocessing pipeline applied to improve keyword matching accuracy. Contraction expansion is performed before stopword removal to ensure negation words (e.g., not) are retained as separate tokens.
>
> - **Set D (VADER + Rule-based)**: Combines the outputs of Set B and Set C. No additional preprocessing required as each component follows its respective pipeline.
>
> - **Set E (ABSA BERT)**: Minimal preprocessing similar to Set B. Stopword removal and lemmatization are excluded as BERT relies on full sentence context and handles subword tokenization (WordPiece) internally.

| Technique | Set B | Set C | Set E |
|---|---|---|---|
| Lowercasing | ✅ | ✅ | ✅ |
| HTML / Special Character Removal | ✅ | ✅ | ✅ |
| Whitespace Normalization | ✅ | ✅ | ✅ |
| Contraction Expansion | ✅ | ✅ (before stopword removal) | ✅ |
| Punctuation Removal (partial) | ✅ | ✅ | ✅ |
| Stopword Removal | ❌ | ✅ | ❌ |
| Tokenization | ❌ | ✅ | ❌ |
| Lemmatization | ❌ | ✅ | ❌ |

In [6]:
# 2.1 Preprocessing Function (Set B and E)

def preprocess_vader_bert(text):
    if pd.isna(text):
        return ""
    # Contraction Expansion
    text = contractions.fix(text)
    # Lowercase
    text = text.lower()
    # Remove HTML tags
    text = re.sub(r'<.*?>', ' ', text)
    # Remove URLs
    text = re.sub(r'http\S+', ' ', text)
    # Remove special characters (keep !, ?, ., ,)
    text = re.sub(r'[^a-zA-Z0-9\s!?.,]', ' ', text)
    # Normalize whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [7]:
# 2.2 Preprocessing Function (Set C)

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_rule_based(text):
    if pd.isna(text):
        return ""
    # Contraction Expansion
    text = contractions.fix(text)
    # Lowercase
    text = text.lower()
    # Remove HTML tags
    text = re.sub(r'<.*?>', ' ', text)
    # Remove URLs
    text = re.sub(r'http\S+', ' ', text)
    # Remove all punctuation and special characters
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    # Normalize whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    # Tokenize
    tokens = word_tokenize(text)
    # Remove stopwords
    tokens = [t for t in tokens if t not in stop_words]
    # Lemmatize
    tokens = [lemmatizer.lemmatize(t) for t in tokens]
    # Remove single character tokens
    tokens = [t for t in tokens if len(t) > 1]
    return ' '.join(tokens)

In [8]:
# 2.3 Apply Preprocessing (Set B and E)
print("Applying Set B/E preprocessing...")
df['cleaned_review_BE'] = df['Full_Review'].apply(preprocess_vader_bert)
print("Done!")

Applying Set B/E preprocessing...
Done!

In [9]:
# 2.4 Apply Preprocessing (Set C)
print("Applying Set C preprocessing...")
df['cleaned_review_C'] = df['Full_Review'].apply(preprocess_rule_based)
print("Done!")

Applying Set C preprocessing...
Done!

## **3. Verify Results**

In [10]:
df.head(3)

,Airline Name,Verified,Type Of Traveller,Seat Type,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended,Covid_Period,review_length,Full_Review,cleaned_review_BE,cleaned_review_C
0,AB Aviation,True,Solo Leisure,Economy Class,4.0,5.0,4.0,4.0,NaN,NaN,3.0,1,0,352,pretty decent airline. Moroni to Moheli. Turne...,pretty decent airline. moroni to moheli. turne...,pretty decent airline moroni moheli turned pre...
1,AB Aviation,True,Solo Leisure,Economy Class,2.0,2.0,1.0,1.0,NaN,NaN,2.0,0,0,689,Not a good airline. Moroni to Anjouan. It is a...,not a good airline. moroni to anjouan. it is a...,good airline moroni anjouan small airline tick...
2,AB Aviation,True,Solo Leisure,Economy Class,2.0,1.0,1.0,1.0,NaN,NaN,2.0,0,0,405,flight was fortunately short. Anjouan to Dzaou...,flight was fortunately short. anjouan to dzaou...,flight fortunately short anjouan dzaoudzi smal...

In [11]:
for i, review in enumerate(df[['Full_Review', 'cleaned_review_BE', 'cleaned_review_C']].values[:50]):
    print(f"=== Review {i+1} ===")
    print(f"Original:\n{review[0]}\n")
    print(f"BE:\n{review[1]}\n")
    print(f"C:\n{review[2]}\n")

=== Review 1 ===
Original:
pretty decent airline. Moroni to Moheli. Turned out to be a pretty decent airline. Online booking worked well, checkin and boarding was fine and the plane looked well maintained. Its a very short flight - just 20 minutes or so so i didn't expect much but they still managed to hand our a bottle of water and some biscuits which i though was very nice. Both flights on time.

BE:
pretty decent airline. moroni to moheli. turned out to be a pretty decent airline. online booking worked well, checkin and boarding was fine and the plane looked well maintained. its a very short flight just 20 minutes or so so i did not expect much but they still managed to hand our a bottle of water and some biscuits which i though was very nice. both flights on time.

C:
pretty decent airline moroni moheli turned pretty decent airline online booking worked well checkin boarding fine plane looked well maintained short flight 20 minute expect much still managed hand bottle water biscuit though nice flight time

=== Review 2 ===
Original:
Not a good airline. Moroni to Anjouan. It is a very small airline. My ticket advised me to turn up at 0800hrs which I did. There was confusion at this small airport. I was then directed to the office of AB Aviation which was still closed. It opened at 0900hrs and I was told that the flight had been put back to 1300hrs and that they had tried to contact me. This could not be true as they did not have my phone number. I was with a local guide and he had not been informed either. I presume that I was bumped off. The later flight did operate but as usual, there was confusion at check-in. The flight was only 30mins and there were no further problems. Not a good airline but it is the only one for Comoros.

BE:
not a good airline. moroni to anjouan. it is a very small airline. my ticket advised me to turn up at 0800hrs which i did. there was confusion at this small airport. i was then directed to the office of ab aviation which was still closed. it opened at 0900hrs and i was told that the flight had been put back to 1300hrs and that they had tried to contact me. this could not be true as they did not have my phone number. i was with a local guide and he had not been informed either. i presume that i was bumped off. the later flight did operate but as usual, there was confusion at check in. the flight was only 30mins and there were no further problems. not a good airline but it is the only one for comoros.

C:
good airline moroni anjouan small airline ticket advised turn 0800hrs confusion small airport directed office ab aviation still closed opened 0900hrs told flight put back 1300hrs tried contact could true phone number local guide informed either presume bumped later flight operate usual confusion check flight 30mins problem good airline one comoros

=== Review 3 ===
Original:
flight was fortunately short. Anjouan to Dzaoudzi. A very small airline and the only airline based in Comoros. Check-in was disorganised because of locals with big packages and disinterested staff. The flight was fortunately short (30 mins). Took off on time and landed on time. With a short flight like there was of course no in-flight entertainment nor cabin service except for biscuits and a bottle of water, which was quite nice!

BE:
flight was fortunately short. anjouan to dzaoudzi. a very small airline and the only airline based in comoros. check in was disorganised because of locals with big packages and disinterested staff. the flight was fortunately short 30 mins . took off on time and landed on time. with a short flight like there was of course no in flight entertainment nor cabin service except for biscuits and a bottle of water, which was quite nice!

C:
flight fortunately short anjouan dzaoudzi small airline airline based comoros check disorganised local big package disinterested staff flight fortunately short 30 min took time landed time short flight like course flight entertainment cabin service except biscuit bottle water quite nice

=== Review 4 ===
Original:
I will never fly again with Adria. Please do a favor yourself and do not fly with Adria. On the route from Munich to Pristina in July 2019 they lost my luggage and for 10 days in a row, despite numerous phone calls they were not able to locate it. 11 days later the luggage arrived at the destination completely ruined. Applying for compensation, they ignored my request. Foolishly again, I booked another flight with them (345 euros) Frankfurt - Pristina in September 2019. They cancelled the flight with no reason 24 hours before the departure. Desperate phone calls to customer service to get anything (rerouting, compensation, etc) were not responded. I will never fly again with Adria. What a disgrace! Shame on you Adria for constantly deceiving your customers.

BE:
i will never fly again with adria. please do a favor yourself and do not fly with adria. on the route from munich to pristina in july 2019 they lost my luggage and for 10 days in a row, despite numerous phone calls they were not able to locate it. 11 days later the luggage arrived at the destination completely ruined. applying for compensation, they ignored my request. foolishly again, i booked another flight with them 345 euros frankfurt pristina in september 2019. they cancelled the flight with no reason 24 hours before the departure. desperate phone calls to customer service to get anything rerouting, compensation, etc were not responded. i will never fly again with adria. what a disgrace! shame on you adria for constantly deceiving your customers.

C:
never fly adria please favor fly adria route munich pristina july 2019 lost luggage 10 day row despite numerous phone call able locate 11 day later luggage arrived destination completely ruined applying compensation ignored request foolishly booked another flight 345 euro frankfurt pristina september 2019 cancelled flight reason 24 hour departure desperate phone call customer service get anything rerouting compensation etc responded never fly adria disgrace shame adria constantly deceiving customer

=== Review 5 ===
Original:
it ruined our last days of holidays. Do not book a flight with this airline! My friend and I should have returned from Sofia to Amsterdam on September 22 and 3 days before, they sent us an SMS informing the flight was cancelled. For 3 straight days we tried to reach the airline and the web agent (e-dreams) and we did not get a solution. Finally, 18 hours before our cancelled flight time, and after 35 minutes on a call (waiting), the airline was able to get us on a flight with Lufthansa. Do not book Adria Airways, it is unreliable and in our case, it ruined our last days of holidays since we needed to be on the phones all day.

BE:
it ruined our last days of holidays. do not book a flight with this airline! my friend and i should have returned from sofia to amsterdam on september 22 and 3 days before, they sent us an sms informing the flight was cancelled. for 3 straight days we tried to reach the airline and the web agent e dreams and we did not get a solution. finally, 18 hours before our cancelled flight time, and after 35 minutes on a call waiting , the airline was able to get us on a flight with lufthansa. do not book adria airways, it is unreliable and in our case, it ruined our last days of holidays since we needed to be on the phones all day.

C:
ruined last day holiday book flight airline friend returned sofia amsterdam september 22 day sent sm informing flight cancelled straight day tried reach airline web agent dream get solution finally 18 hour cancelled flight time 35 minute call waiting airline able get flight lufthansa book adria airway unreliable case ruined last day holiday since needed phone day

=== Review 6 ===
Original:
Had very bad experience. Had very bad experience with rerouted and cancelled flights last weekend with Adria airways. Original Route was Ljubljana to Sarajevo return. Two weeks before i received an email that the flight was cancelled. Offered route change was Ljubljana to Sarajevo via Munich. Flight back changed to Sarajevo-Pristina-Ljubljana. I accepted. The first flight via Munich was ok. Two hours before the return flight I got the email that the flight was cancelled. I had to rebook via hotline and had to accept a flight with Croatian to Zagreb. I reached Ljubljana 4 h later and had to organize Transport from Zagreb to Ljubljana on my own cost. Do not book flights with Adria airways. I heard that their financial situation is very very bad.

BE:
had very bad experience. had very bad experience with rerouted and cancelled flights last weekend with adria airways. original route was ljubljana to sarajevo return. two weeks before i received an email that the flight was cancelled. offered route change was ljubljana to sarajevo via munich. flight back changed to sarajevo pristina ljubljana. i accepted. the first flight via munich was ok. two hours before the return flight i got the email that the flight was cancelled. i had to rebook via hotline and had to accept a flight with croatian to zagreb. i reached ljubljana 4 h later and had to organize transport from zagreb to ljubljana on my own cost. do not book flights with adria airways. i heard that their financial situation is very very bad.

C:
bad experience bad experience rerouted cancelled flight last weekend adria airway original route ljubljana sarajevo return two week received email flight cancelled offered route change ljubljana sarajevo via munich flight back changed sarajevo pristina ljubljana accepted first flight via munich ok two hour return flight got email flight cancelled rebook via hotline accept flight croatian zagreb reached ljubljana later organize transport zagreb ljubljana cost book flight adria airway heard financial situation bad

=== Review 7 ===
Original:
worse than the budget airlines. Ljubljana to Zürich. Firstly, Ljubljana airport is terrible. Badly trained staff, unfriendly. Toilets are very dirty. Flight 2 hours delayed without any information. There is no Information desk so questions aren‘t possible. Never again will use this airline. Its even worse than the budget airlines and thats difficult.

BE:
worse than the budget airlines. ljubljana to z rich. firstly, ljubljana airport is terrible. badly trained staff, unfriendly. toilets are very dirty. flight 2 hours delayed without any information. there is no information desk so questions aren t possible. never again will use this airline. its even worse than the budget airlines and that is difficult.

C:
worse budget airline ljubljana rich firstly ljubljana airport terrible badly trained staff unfriendly toilet dirty flight hour delayed without information information desk question possible never use airline even worse budget airline difficult

=== Review 8 ===
Original:
book another company. First of all, I am not complaining about a specific flight. I am a Lufthansa frequent Flyer and I normally fly the route Munich - Timisoara. This summer season Lufthansa offered the flights on this route to Adria Airways, as they are a star alliance member. I can only tell that I have the worst experiences with them. In over 90% of the cases they are late, they don't fly on time. Always they offer the same excuse: they have no slot free. This is an unacceptable excuse, as all other companies flying on similar coridors seem not to have this problem. In addition, as LH Cityline was operating these flights I have almost never heard this excuse, or had this problem. I am flying on this route for 6 years already. They started also to cancel some flights. Maybe combine 2 flights into 1 to spare some money, who knows. The cabin crew is decent - not wow, not bad - but there also also situations when the staff are really rude and not customer oriented. I would recommend anyone to fly with this company. If you have the chance, book another company!

BE:
book another company. first of all, i am not complaining about a specific flight. i am a lufthansa frequent flyer and i normally fly the route munich timisoara. this summer season lufthansa offered the flights on this route to adria airways, as they are a star alliance member. i can only tell that i have the worst experiences with them. in over 90 of the cases they are late, they do not fly on time. always they offer the same excuse they have no slot free. this is an unacceptable excuse, as all other companies flying on similar coridors seem not to have this problem. in addition, as lh cityline was operating these flights i have almost never heard this excuse, or had this problem. i am flying on this route for 6 years already. they started also to cancel some flights. maybe combine 2 flights into 1 to spare some money, who knows. the cabin crew is decent not wow, not bad but there also also situations when the staff are really rude and not customer oriented. i would recommend anyone to fly with this company. if you have the chance, book another company!

C:
book another company first complaining specific flight lufthansa frequent flyer normally fly route munich timisoara summer season lufthansa offered flight route adria airway star alliance member tell worst experience 90 case late fly time always offer excuse slot free unacceptable excuse company flying similar coridors seem problem addition lh cityline operating flight almost never heard excuse problem flying route year already started also cancel flight maybe combine flight spare money know cabin crew decent wow bad also also situation staff really rude customer oriented would recommend anyone fly company chance book another company

=== Review 9 ===
Original:
combined two flights. Worst Airline ever! They combined two flights to save costs. Instead of flying Pristina - Ljubliana - Zürich we now fly Pristina - Ljubliana - München - Zürich. Now we arrive 2.5h later at our destination.

BE:
combined two flights. worst airline ever! they combined two flights to save costs. instead of flying pristina ljubliana z rich we now fly pristina ljubliana m nchen z rich. now we arrive 2.5h later at our destination.

C:
combined two flight worst airline ever combined two flight save cost instead flying pristina ljubliana rich fly pristina ljubliana nchen rich arrive 5h later destination

=== Review 10 ===
Original:
the crew was nice. Ljubljana to Munich. The homebase airport of Adria Airways is Ljubljana and it very small, relaxing and convenient. It is surrounded by the Alps and the departure was fantastic. The airplane was modern and the crew was nice. Ontime departure. Drinks without alcohol were free and I paid 4€ for my white wine. Considering that I had a cheap ticket I cannot complain. Upgrades would have been available for 30€ - which includes the lounge.

BE:
the crew was nice. ljubljana to munich. the homebase airport of adria airways is ljubljana and it very small, relaxing and convenient. it is surrounded by the alps and the departure was fantastic. the airplane was modern and the crew was nice. ontime departure. drinks without alcohol were free and i paid 4 for my white wine. considering that i had a cheap ticket i cannot complain. upgrades would have been available for 30 which includes the lounge.

C:
crew nice ljubljana munich homebase airport adria airway ljubljana small relaxing convenient surrounded alp departure fantastic airplane modern crew nice ontime departure drink without alcohol free paid white wine considering cheap ticket complain upgrade would available 30 includes lounge

=== Review 11 ===
Original:
Very bad experience overall. Zurich to Ljubljana. Very poor customer service. Flight was cancelled without sending any email confirmation. The flight I was rebooked seemed to be overbooked at the beginning (which was not true)and we had to wait 30 min to have our ticket changed. Very bad experience overall.

BE:
very bad experience overall. zurich to ljubljana. very poor customer service. flight was cancelled without sending any email confirmation. the flight i was rebooked seemed to be overbooked at the beginning which was not true and we had to wait 30 min to have our ticket changed. very bad experience overall.

C:
bad experience overall zurich ljubljana poor customer service flight cancelled without sending email confirmation flight rebooked seemed overbooked beginning true wait 30 min ticket changed bad experience overall

=== Review 12 ===
Original:
bad customer service. Vienna to Sofia. The flight was delayed by 2 hours. The cabin crew was annoyed that they had to offer drinks to the passengers and passing by announced they would only give one drink per customer. And coffee was a nuisance and they made it clear, even though it was on their cart. The questions would normally go "would you drink anything?" and not "what would you like to drink?". Very bad customer service.

BE:
bad customer service. vienna to sofia. the flight was delayed by 2 hours. the cabin crew was annoyed that they had to offer drinks to the passengers and passing by announced they would only give one drink per customer. and coffee was a nuisance and they made it clear, even though it was on their cart. the questions would normally go would you drink anything? and not what would you like to drink? . very bad customer service.

C:
bad customer service vienna sofia flight delayed hour cabin crew annoyed offer drink passenger passing announced would give one drink per customer coffee nuisance made clear even though cart question would normally go would drink anything would like drink bad customer service

=== Review 13 ===
Original:
overall very poor. We were traveling from Paris to Skopje on May 4th, via Ljubljana. Our flight from Ljubljana to Skopje, was canceled 10 days before our departure for no reason, leaving us in the middle of our connection at Ljubljana. Even if the company booked a hotel for us and made sure we could take a flight the next day, it prevented us from enjoying one more day in Macedonia. The company had agreed to reimburse the hostel night we had already paid but more than two months after our claim we still have no reply from the company. I e-mailed the company two times, called them on multiple occasion. The company said I would be reimbursed after 2 months. 2 months later, I still have not received anything. The experience with Adria Airways was overall very poor : - flight canceled for no reason - 2 out of 4 of the flights we took were delayed - terrible customer service, unable to give any answer to our online claim and not reimbursing the hostel night we had already paid

BE:
overall very poor. we were traveling from paris to skopje on may 4th, via ljubljana. our flight from ljubljana to skopje, was canceled 10 days before our departure for no reason, leaving us in the middle of our connection at ljubljana. even if the company booked a hotel for us and made sure we could take a flight the next day, it prevented us from enjoying one more day in macedonia. the company had agreed to reimburse the hostel night we had already paid but more than two months after our claim we still have no reply from the company. i e mailed the company two times, called them on multiple occasion. the company said i would be reimbursed after 2 months. 2 months later, i still have not received anything. the experience with adria airways was overall very poor flight canceled for no reason 2 out of 4 of the flights we took were delayed terrible customer service, unable to give any answer to our online claim and not reimbursing the hostel night we had already paid

C:

> ### **Scraping Error Removal**
>
> During web scraping, the Skytrax review pages included a recurring template phrase at the beginning of certain reviews in the format:
> *"[Airline Name] customer review. [review content]..."*
>
> For example (Starting from Review #43):
> - *"Adria Airways customer review. Flew Zurich-Ljubljana..."*
> - *"Afriqiyah Airways customer review. Gatwick to..."*
>
> This phrase carries no sentiment or aspect information and is therefore removed prior to preprocessing.

In [12]:
# Check how many reviews contain "customer review" pattern
pattern_count = df['Full_Review'].str.contains('customer review', case=False, na=False).sum()
print(f"Reviews containing 'customer review': {pattern_count}")

# See examples from different airlines
mask = df['Full_Review'].str.contains('customer review', case=False, na=False)
df[mask][['Airline Name', 'Full_Review']].head(10)

Reviews containing 'customer review': 4032

     Airline Name                                        Full_Review
42  Adria Airways  Adria Airways customer review. Outbound flight...
43  Adria Airways  Adria Airways customer review. Flew Zurich-Lju...
44  Adria Airways  Adria Airways customer review. Adria serves th...
45  Adria Airways  Adria Airways customer review. WAW-SKJ Economy...
46  Adria Airways  Adria Airways customer review. Sarajevo-Frankf...
47  Adria Airways  Adria Airways customer review. I had flights f...
48  Adria Airways  Adria Airways customer review. LJU to FRA and ...
49  Adria Airways  Adria Airways customer review. On my Ljubljana...
50  Adria Airways  Adria Airways customer review. Flights from LJ...
51  Adria Airways  Adria Airways customer review. I was very sati...

In [13]:
# Remove "[Airline Name] customer review" boilerplate
def remove_customer_review(text):
    if pd.isna(text):
        return text
    # Remove pattern like "Airline Name customer review."
    text = re.sub(r'[\w\s]+ customer review\.?\s*', '', text, flags=re.IGNORECASE)
    return text.strip()

# Apply to Full_Review before preprocessing
df['Full_Review'] = df['Full_Review'].apply(remove_customer_review)

In [14]:
# Re-apply preprocessing after boilerplate removal

print("Re-applying Set B/E preprocessing...")
df['cleaned_review_BE'] = df['Full_Review'].apply(preprocess_vader_bert)
print("Done!")

print("Re-applying Set C preprocessing...")
df['cleaned_review_C'] = df['Full_Review'].apply(preprocess_rule_based)
print("Done!")

Re-applying Set B/E preprocessing...
Done!
Re-applying Set C preprocessing...
Done!

In [15]:
for i, review in enumerate(df[['Full_Review', 'cleaned_review_BE', 'cleaned_review_C']].values[:50]):
    print(f"=== Review {i+1} ===")
    print(f"Original:\n{review[0]}\n")
    print(f"BE:\n{review[1]}\n")
    print(f"C:\n{review[2]}\n")

=== Review 1 ===
Original:
pretty decent airline. Moroni to Moheli. Turned out to be a pretty decent airline. Online booking worked well, checkin and boarding was fine and the plane looked well maintained. Its a very short flight - just 20 minutes or so so i didn't expect much but they still managed to hand our a bottle of water and some biscuits which i though was very nice. Both flights on time.

BE:
pretty decent airline. moroni to moheli. turned out to be a pretty decent airline. online booking worked well, checkin and boarding was fine and the plane looked well maintained. its a very short flight just 20 minutes or so so i did not expect much but they still managed to hand our a bottle of water and some biscuits which i though was very nice. both flights on time.

C:
pretty decent airline moroni moheli turned pretty decent airline online booking worked well checkin boarding fine plane looked well maintained short flight 20 minute expect much still managed hand bottle water biscuit though nice flight time

=== Review 2 ===
Original:
Not a good airline. Moroni to Anjouan. It is a very small airline. My ticket advised me to turn up at 0800hrs which I did. There was confusion at this small airport. I was then directed to the office of AB Aviation which was still closed. It opened at 0900hrs and I was told that the flight had been put back to 1300hrs and that they had tried to contact me. This could not be true as they did not have my phone number. I was with a local guide and he had not been informed either. I presume that I was bumped off. The later flight did operate but as usual, there was confusion at check-in. The flight was only 30mins and there were no further problems. Not a good airline but it is the only one for Comoros.

BE:
not a good airline. moroni to anjouan. it is a very small airline. my ticket advised me to turn up at 0800hrs which i did. there was confusion at this small airport. i was then directed to the office of ab aviation which was still closed. it opened at 0900hrs and i was told that the flight had been put back to 1300hrs and that they had tried to contact me. this could not be true as they did not have my phone number. i was with a local guide and he had not been informed either. i presume that i was bumped off. the later flight did operate but as usual, there was confusion at check in. the flight was only 30mins and there were no further problems. not a good airline but it is the only one for comoros.

C:
good airline moroni anjouan small airline ticket advised turn 0800hrs confusion small airport directed office ab aviation still closed opened 0900hrs told flight put back 1300hrs tried contact could true phone number local guide informed either presume bumped later flight operate usual confusion check flight 30mins problem good airline one comoros

=== Review 3 ===
Original:
flight was fortunately short. Anjouan to Dzaoudzi. A very small airline and the only airline based in Comoros. Check-in was disorganised because of locals with big packages and disinterested staff. The flight was fortunately short (30 mins). Took off on time and landed on time. With a short flight like there was of course no in-flight entertainment nor cabin service except for biscuits and a bottle of water, which was quite nice!

BE:
flight was fortunately short. anjouan to dzaoudzi. a very small airline and the only airline based in comoros. check in was disorganised because of locals with big packages and disinterested staff. the flight was fortunately short 30 mins . took off on time and landed on time. with a short flight like there was of course no in flight entertainment nor cabin service except for biscuits and a bottle of water, which was quite nice!

C:
flight fortunately short anjouan dzaoudzi small airline airline based comoros check disorganised local big package disinterested staff flight fortunately short 30 min took time landed time short flight like course flight entertainment cabin service except biscuit bottle water quite nice

=== Review 4 ===
Original:
I will never fly again with Adria. Please do a favor yourself and do not fly with Adria. On the route from Munich to Pristina in July 2019 they lost my luggage and for 10 days in a row, despite numerous phone calls they were not able to locate it. 11 days later the luggage arrived at the destination completely ruined. Applying for compensation, they ignored my request. Foolishly again, I booked another flight with them (345 euros) Frankfurt - Pristina in September 2019. They cancelled the flight with no reason 24 hours before the departure. Desperate phone calls to customer service to get anything (rerouting, compensation, etc) were not responded. I will never fly again with Adria. What a disgrace! Shame on you Adria for constantly deceiving your customers.

BE:
i will never fly again with adria. please do a favor yourself and do not fly with adria. on the route from munich to pristina in july 2019 they lost my luggage and for 10 days in a row, despite numerous phone calls they were not able to locate it. 11 days later the luggage arrived at the destination completely ruined. applying for compensation, they ignored my request. foolishly again, i booked another flight with them 345 euros frankfurt pristina in september 2019. they cancelled the flight with no reason 24 hours before the departure. desperate phone calls to customer service to get anything rerouting, compensation, etc were not responded. i will never fly again with adria. what a disgrace! shame on you adria for constantly deceiving your customers.

C:
never fly adria please favor fly adria route munich pristina july 2019 lost luggage 10 day row despite numerous phone call able locate 11 day later luggage arrived destination completely ruined applying compensation ignored request foolishly booked another flight 345 euro frankfurt pristina september 2019 cancelled flight reason 24 hour departure desperate phone call customer service get anything rerouting compensation etc responded never fly adria disgrace shame adria constantly deceiving customer

=== Review 5 ===
Original:
it ruined our last days of holidays. Do not book a flight with this airline! My friend and I should have returned from Sofia to Amsterdam on September 22 and 3 days before, they sent us an SMS informing the flight was cancelled. For 3 straight days we tried to reach the airline and the web agent (e-dreams) and we did not get a solution. Finally, 18 hours before our cancelled flight time, and after 35 minutes on a call (waiting), the airline was able to get us on a flight with Lufthansa. Do not book Adria Airways, it is unreliable and in our case, it ruined our last days of holidays since we needed to be on the phones all day.

BE:
it ruined our last days of holidays. do not book a flight with this airline! my friend and i should have returned from sofia to amsterdam on september 22 and 3 days before, they sent us an sms informing the flight was cancelled. for 3 straight days we tried to reach the airline and the web agent e dreams and we did not get a solution. finally, 18 hours before our cancelled flight time, and after 35 minutes on a call waiting , the airline was able to get us on a flight with lufthansa. do not book adria airways, it is unreliable and in our case, it ruined our last days of holidays since we needed to be on the phones all day.

C:
ruined last day holiday book flight airline friend returned sofia amsterdam september 22 day sent sm informing flight cancelled straight day tried reach airline web agent dream get solution finally 18 hour cancelled flight time 35 minute call waiting airline able get flight lufthansa book adria airway unreliable case ruined last day holiday since needed phone day

=== Review 6 ===
Original:
Had very bad experience. Had very bad experience with rerouted and cancelled flights last weekend with Adria airways. Original Route was Ljubljana to Sarajevo return. Two weeks before i received an email that the flight was cancelled. Offered route change was Ljubljana to Sarajevo via Munich. Flight back changed to Sarajevo-Pristina-Ljubljana. I accepted. The first flight via Munich was ok. Two hours before the return flight I got the email that the flight was cancelled. I had to rebook via hotline and had to accept a flight with Croatian to Zagreb. I reached Ljubljana 4 h later and had to organize Transport from Zagreb to Ljubljana on my own cost. Do not book flights with Adria airways. I heard that their financial situation is very very bad.

BE:
had very bad experience. had very bad experience with rerouted and cancelled flights last weekend with adria airways. original route was ljubljana to sarajevo return. two weeks before i received an email that the flight was cancelled. offered route change was ljubljana to sarajevo via munich. flight back changed to sarajevo pristina ljubljana. i accepted. the first flight via munich was ok. two hours before the return flight i got the email that the flight was cancelled. i had to rebook via hotline and had to accept a flight with croatian to zagreb. i reached ljubljana 4 h later and had to organize transport from zagreb to ljubljana on my own cost. do not book flights with adria airways. i heard that their financial situation is very very bad.

C:
bad experience bad experience rerouted cancelled flight last weekend adria airway original route ljubljana sarajevo return two week received email flight cancelled offered route change ljubljana sarajevo via munich flight back changed sarajevo pristina ljubljana accepted first flight via munich ok two hour return flight got email flight cancelled rebook via hotline accept flight croatian zagreb reached ljubljana later organize transport zagreb ljubljana cost book flight adria airway heard financial situation bad

=== Review 7 ===
Original:
worse than the budget airlines. Ljubljana to Zürich. Firstly, Ljubljana airport is terrible. Badly trained staff, unfriendly. Toilets are very dirty. Flight 2 hours delayed without any information. There is no Information desk so questions aren‘t possible. Never again will use this airline. Its even worse than the budget airlines and thats difficult.

BE:
worse than the budget airlines. ljubljana to z rich. firstly, ljubljana airport is terrible. badly trained staff, unfriendly. toilets are very dirty. flight 2 hours delayed without any information. there is no information desk so questions aren t possible. never again will use this airline. its even worse than the budget airlines and that is difficult.

C:
worse budget airline ljubljana rich firstly ljubljana airport terrible badly trained staff unfriendly toilet dirty flight hour delayed without information information desk question possible never use airline even worse budget airline difficult

=== Review 8 ===
Original:
book another company. First of all, I am not complaining about a specific flight. I am a Lufthansa frequent Flyer and I normally fly the route Munich - Timisoara. This summer season Lufthansa offered the flights on this route to Adria Airways, as they are a star alliance member. I can only tell that I have the worst experiences with them. In over 90% of the cases they are late, they don't fly on time. Always they offer the same excuse: they have no slot free. This is an unacceptable excuse, as all other companies flying on similar coridors seem not to have this problem. In addition, as LH Cityline was operating these flights I have almost never heard this excuse, or had this problem. I am flying on this route for 6 years already. They started also to cancel some flights. Maybe combine 2 flights into 1 to spare some money, who knows. The cabin crew is decent - not wow, not bad - but there also also situations when the staff are really rude and not customer oriented. I would recommend anyone to fly with this company. If you have the chance, book another company!

BE:
book another company. first of all, i am not complaining about a specific flight. i am a lufthansa frequent flyer and i normally fly the route munich timisoara. this summer season lufthansa offered the flights on this route to adria airways, as they are a star alliance member. i can only tell that i have the worst experiences with them. in over 90 of the cases they are late, they do not fly on time. always they offer the same excuse they have no slot free. this is an unacceptable excuse, as all other companies flying on similar coridors seem not to have this problem. in addition, as lh cityline was operating these flights i have almost never heard this excuse, or had this problem. i am flying on this route for 6 years already. they started also to cancel some flights. maybe combine 2 flights into 1 to spare some money, who knows. the cabin crew is decent not wow, not bad but there also also situations when the staff are really rude and not customer oriented. i would recommend anyone to fly with this company. if you have the chance, book another company!

C:
book another company first complaining specific flight lufthansa frequent flyer normally fly route munich timisoara summer season lufthansa offered flight route adria airway star alliance member tell worst experience 90 case late fly time always offer excuse slot free unacceptable excuse company flying similar coridors seem problem addition lh cityline operating flight almost never heard excuse problem flying route year already started also cancel flight maybe combine flight spare money know cabin crew decent wow bad also also situation staff really rude customer oriented would recommend anyone fly company chance book another company

=== Review 9 ===
Original:
combined two flights. Worst Airline ever! They combined two flights to save costs. Instead of flying Pristina - Ljubliana - Zürich we now fly Pristina - Ljubliana - München - Zürich. Now we arrive 2.5h later at our destination.

BE:
combined two flights. worst airline ever! they combined two flights to save costs. instead of flying pristina ljubliana z rich we now fly pristina ljubliana m nchen z rich. now we arrive 2.5h later at our destination.

C:
combined two flight worst airline ever combined two flight save cost instead flying pristina ljubliana rich fly pristina ljubliana nchen rich arrive 5h later destination

=== Review 10 ===
Original:
the crew was nice. Ljubljana to Munich. The homebase airport of Adria Airways is Ljubljana and it very small, relaxing and convenient. It is surrounded by the Alps and the departure was fantastic. The airplane was modern and the crew was nice. Ontime departure. Drinks without alcohol were free and I paid 4€ for my white wine. Considering that I had a cheap ticket I cannot complain. Upgrades would have been available for 30€ - which includes the lounge.

BE:
the crew was nice. ljubljana to munich. the homebase airport of adria airways is ljubljana and it very small, relaxing and convenient. it is surrounded by the alps and the departure was fantastic. the airplane was modern and the crew was nice. ontime departure. drinks without alcohol were free and i paid 4 for my white wine. considering that i had a cheap ticket i cannot complain. upgrades would have been available for 30 which includes the lounge.

C:
crew nice ljubljana munich homebase airport adria airway ljubljana small relaxing convenient surrounded alp departure fantastic airplane modern crew nice ontime departure drink without alcohol free paid white wine considering cheap ticket complain upgrade would available 30 includes lounge

=== Review 11 ===
Original:
Very bad experience overall. Zurich to Ljubljana. Very poor customer service. Flight was cancelled without sending any email confirmation. The flight I was rebooked seemed to be overbooked at the beginning (which was not true)and we had to wait 30 min to have our ticket changed. Very bad experience overall.

BE:
very bad experience overall. zurich to ljubljana. very poor customer service. flight was cancelled without sending any email confirmation. the flight i was rebooked seemed to be overbooked at the beginning which was not true and we had to wait 30 min to have our ticket changed. very bad experience overall.

C:
bad experience overall zurich ljubljana poor customer service flight cancelled without sending email confirmation flight rebooked seemed overbooked beginning true wait 30 min ticket changed bad experience overall

=== Review 12 ===
Original:
bad customer service. Vienna to Sofia. The flight was delayed by 2 hours. The cabin crew was annoyed that they had to offer drinks to the passengers and passing by announced they would only give one drink per customer. And coffee was a nuisance and they made it clear, even though it was on their cart. The questions would normally go "would you drink anything?" and not "what would you like to drink?". Very bad customer service.

BE:
bad customer service. vienna to sofia. the flight was delayed by 2 hours. the cabin crew was annoyed that they had to offer drinks to the passengers and passing by announced they would only give one drink per customer. and coffee was a nuisance and they made it clear, even though it was on their cart. the questions would normally go would you drink anything? and not what would you like to drink? . very bad customer service.

C:
bad customer service vienna sofia flight delayed hour cabin crew annoyed offer drink passenger passing announced would give one drink per customer coffee nuisance made clear even though cart question would normally go would drink anything would like drink bad customer service

=== Review 13 ===
Original:
overall very poor. We were traveling from Paris to Skopje on May 4th, via Ljubljana. Our flight from Ljubljana to Skopje, was canceled 10 days before our departure for no reason, leaving us in the middle of our connection at Ljubljana. Even if the company booked a hotel for us and made sure we could take a flight the next day, it prevented us from enjoying one more day in Macedonia. The company had agreed to reimburse the hostel night we had already paid but more than two months after our claim we still have no reply from the company. I e-mailed the company two times, called them on multiple occasion. The company said I would be reimbursed after 2 months. 2 months later, I still have not received anything. The experience with Adria Airways was overall very poor : - flight canceled for no reason - 2 out of 4 of the flights we took were delayed - terrible customer service, unable to give any answer to our online claim and not reimbursing the hostel night we had already paid

BE:
overall very poor. we were traveling from paris to skopje on may 4th, via ljubljana. our flight from ljubljana to skopje, was canceled 10 days before our departure for no reason, leaving us in the middle of our connection at ljubljana. even if the company booked a hotel for us and made sure we could take a flight the next day, it prevented us from enjoying one more day in macedonia. the company had agreed to reimburse the hostel night we had already paid but more than two months after our claim we still have no reply from the company. i e mailed the company two times, called them on multiple occasion. the company said i would be reimbursed after 2 months. 2 months later, i still have not received anything. the experience with adria airways was overall very poor flight canceled for no reason 2 out of 4 of the flights we took were delayed terrible customer service, unable to give any answer to our online claim and not reimbursing the hostel night we had already paid

C:

## **4. Save Processed Dataset**

In [17]:
import os
os.makedirs('../1_data/processed', exist_ok=True)
out_path = '../1_data/processed/02_preprocessed.csv'
df.to_csv(out_path, index=False)
print(f"Saved → {out_path}")
print("\n")
print(f"Final shape: {df.shape}")
df.info()

Saved → ../1_data/processed/02_preprocessed.csv


Final shape: (22980, 17)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22980 entries, 0 to 22979
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Airline Name            22980 non-null  object
 1   Verified                22980 non-null  bool
 2   Type Of Traveller       22980 non-null  object
 3   Seat Type               22980 non-null  object
 4   Seat Comfort            18763 non-null  float64
 5   Cabin Staff Service     18673 non-null  float64
 6   Food & Beverages        14162 non-null  float64
 7   Ground Service          18292 non-null  float64
 8   Inflight Entertainment  10245 non-null  float64
 9   Wifi & Connectivity     5896 non-null   float64
 10  Value For Money         21806 non-null  float64
 11  Recommended             22980 non-null  int64
 12  Covid_Period            22980 non-null  int64
 13  review_length           22980 non-null  int64
 14  Full_Review             22980 non-null  object
 15  cleaned_review_BE       22980 non-null  object
 16  cleaned_review_C        22980 non-null  object
dtypes: bool(1), float64(7), int64(3), object(6)
memory usage: 2.8+ MB